name: Audit

on: 
  push: 
    branches: [main]
  pull_request:
    branches: [main]
  jobs:
    audit:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v2
      with: 
        go-version: 1.24

    - name: Verify Dependencies
      run: go mod verify

    - name: Build
      run: go Build -v ./...

    - name: Run go vet
      run: go vet ./...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest
    
    - name: Run staticcheck
      run: staticcheck ./...

    - name: 
      run: go test -race ./...


